version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./pdfs:/var/www/pdfs:ro
    restart: always

  portfolio:
    build: ./apps/portfolio
    restart: always
    depends_on:
      - nginx

  habitsior-frontend:
    build: ./apps/habitsior-frontend
    restart: always
    env_file:
      - ./apps/habitsior-frontend/.env
    depends_on:
      - nginx

  habitsior-backend:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.9
    volumes:
      - ./apps/habitsior-backend:/app
    command: "/app/start-prod.sh"
    env_file:
      - ./apps/habitsior-backend/.env
    restart: always
    depends_on:
      - nginx

  onboarcerer-frontend:
    build: ./apps/onboarcerer-frontend
    restart: always
    env_file:
      - ./apps/onboarcerer-frontend/.env
    depends_on:
      - nginx

  fakenewsflush-frontend:
    build: ./apps/fakenewsflush-frontend
    restart: always
    env_file:
      - ./apps/fakenewsflush-frontend/.env
    depends_on:
      - nginx

  fakenewsflush-backend:
    build: ./apps/fakenewsflush-backend
    restart: always
    depends_on:
      - nginx
